[book]
authors = ["Ionizing"]
language = "en"
multilingual = false
src = "src"
title = "NAMD-LMI Manual"

[build]
build-dir = "book"
create-missing = true
use-default-preprocessor = true

[output.html]
default-theme = "rust"
mathjax-support = true

[output.html.fold]
enable = true
level = 1

[output.markdown]
